/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "finances" CASCADE;

CREATE TABLE "finances" (
  "digits" INTEGER NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "guaincome" INTEGER NOT NULL,
  "guaexpend" INTEGER NOT NULL,
  "rembudget" INTEGER NOT NULL,
  "monthbudget" INTEGER NOT NULL,
  "weekcounter" INTEGER NOT NULL,
  "percentsave" INTEGER NOT NULL,
  "percentwarning" INTEGER NOT NULL);

